version: "2"

linters:
  default: none
  enable:
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - fatcontext
    - forcetypeassert
    - gochecksumtype
    - gosec
    - govet
    - ineffassign
    - makezero
    - musttag
    - nilerr
    - nilnesserr
    - nilnil
    - nolintlint
    - nosprintfhostport
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unused
  settings:
    govet:
      enable:
        - shadow
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
